name: e_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Stripe and Cloud Functions dependencies
  flutter_stripe: ^10.1.1
  cloud_functions: ^5.0.1

  firebase_core: ^3.14.0
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^1.1.2
  provider: ^6.1.5
  uuid: ^4.5.1
  logger: ^2.5.0
  rxdart: ^0.28.0
  supabase_flutter: ^2.0.0
  http: ^1.2.1
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.6
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true