// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1MnRnqgBTstEn0snA_u5tP1Nc7PNVN6U',
    appId: '1:1008367221463:web:20ae8e4fda8c6f0dc74e92',
    messagingSenderId: '1008367221463',
    projectId: 'ecommerce-82fc9',
    authDomain: 'ecommerce-82fc9.firebaseapp.com',
    storageBucket: 'ecommerce-82fc9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEx2F6btLVmNqdJ8OnjYh6_M3R5N_tSjQ',
    appId: '1:1008367221463:android:b93467edf059eb5ac74e92',
    messagingSenderId: '1008367221463',
    projectId: 'ecommerce-82fc9',
    storageBucket: 'ecommerce-82fc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgHVt23W_yoZF_l1RRnPz6wSB-byuxJys',
    appId: '1:1008367221463:ios:65bf7979bd7196dbc74e92',
    messagingSenderId: '1008367221463',
    projectId: 'ecommerce-82fc9',
    storageBucket: 'ecommerce-82fc9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgHVt23W_yoZF_l1RRnPz6wSB-byuxJys',
    appId: '1:1008367221463:ios:65bf7979bd7196dbc74e92',
    messagingSenderId: '1008367221463',
    projectId: 'ecommerce-82fc9',
    storageBucket: 'ecommerce-82fc9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1MnRnqgBTstEn0snA_u5tP1Nc7PNVN6U',
    appId: '1:1008367221463:web:44dcd3b22ec38a25c74e92',
    messagingSenderId: '1008367221463',
    projectId: 'ecommerce-82fc9',
    authDomain: 'ecommerce-82fc9.firebaseapp.com',
    storageBucket: 'ecommerce-82fc9.firebasestorage.app',
  );

}